name: '🏗️ Build Plugin'

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
    inputs:
      dotnet-version:
        required: false
        default: "6.0.x"
        description: "The .NET version to setup for the build"
        type: string
      dotnet-target:
        required: false
        default: "net6.0"
        description: "The .NET target to set for JPRM"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Setup .NET
        uses: actions/setup-dotnet@607fce577a46308457984d59e4954e075820f10a # tag=v3.0.3
        with:
          dotnet-version: "${{ inputs.dotnet-version }}"

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          retention-days: 30
          if-no-files-found: error
          path: Nick.Plugin.Jellyscrub/bin/Release/net6.0/Nick.Plugin.Jellyscrub.dll
